on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  frizbee_action_test:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          actions: tests/workflows
          dockerfiles: tests/dockerfiles
          kubernetes: tests/k8s
          docker_compose: tests/docker_compose
          open_pr: true
          fail_on_unpinned: true